In [2]:
import torch
theta_numerator = torch.arange(0, 512, 2).float() 

print(theta_numerator.shape)
print(theta_numerator)

torch.Size([256])
tensor([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,
         48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,
         72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,
         96.,  98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118.,
        120., 122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
        144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164., 166.,
        168., 170., 172., 174., 176., 178., 180., 182., 184., 186., 188., 190.,
        192., 194., 196., 198., 200., 202., 204., 206., 208., 210., 212., 214.,
        216., 218., 220., 222., 224., 226., 228., 230., 232., 234., 236., 238.,
        240., 242., 244., 246., 248., 250., 252., 254., 256., 258., 260., 262.,
        264., 266., 268., 270., 272., 274., 276., 278., 280., 282., 284., 286.,
        288., 290., 29

In [3]:
theta = 1.0 / (10000.0 ** (theta_numerator / 512))
print(theta.shape)
print(theta)

torch.Size([256])
tensor([1.0000e+00, 9.6466e-01, 9.3057e-01, 8.9769e-01, 8.6596e-01, 8.3536e-01,
        8.0584e-01, 7.7737e-01, 7.4989e-01, 7.2339e-01, 6.9783e-01, 6.7317e-01,
        6.4938e-01, 6.2643e-01, 6.0430e-01, 5.8294e-01, 5.6234e-01, 5.4247e-01,
        5.2330e-01, 5.0481e-01, 4.8697e-01, 4.6976e-01, 4.5316e-01, 4.3714e-01,
        4.2170e-01, 4.0679e-01, 3.9242e-01, 3.7855e-01, 3.6517e-01, 3.5227e-01,
        3.3982e-01, 3.2781e-01, 3.1623e-01, 3.0505e-01, 2.9427e-01, 2.8387e-01,
        2.7384e-01, 2.6416e-01, 2.5483e-01, 2.4582e-01, 2.3714e-01, 2.2876e-01,
        2.2067e-01, 2.1288e-01, 2.0535e-01, 1.9810e-01, 1.9110e-01, 1.8434e-01,
        1.7783e-01, 1.7154e-01, 1.6548e-01, 1.5963e-01, 1.5399e-01, 1.4855e-01,
        1.4330e-01, 1.3824e-01, 1.3335e-01, 1.2864e-01, 1.2409e-01, 1.1971e-01,
        1.1548e-01, 1.1140e-01, 1.0746e-01, 1.0366e-01, 1.0000e-01, 9.6466e-02,
        9.3057e-02, 8.9769e-02, 8.6596e-02, 8.3536e-02, 8.0584e-02, 7.7737e-02,
        7.4989e-02, 7.

In [4]:
m =  torch.arange(50) # (seq_len, 1)
print(m.shape)
print(m)

torch.Size([50])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])


In [5]:
freqs = torch.outer(m, theta).float()
print(freqs.shape)
print(freqs)

torch.Size([50, 256])
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.0000e+00, 9.6466e-01, 9.3057e-01,  ..., 1.1140e-04, 1.0746e-04,
         1.0366e-04],
        [2.0000e+00, 1.9293e+00, 1.8611e+00,  ..., 2.2279e-04, 2.1492e-04,
         2.0733e-04],
        ...,
        [4.7000e+01, 4.5339e+01, 4.3737e+01,  ..., 5.2357e-03, 5.0507e-03,
         4.8722e-03],
        [4.8000e+01, 4.6304e+01, 4.4667e+01,  ..., 5.3471e-03, 5.1581e-03,
         4.9758e-03],
        [4.9000e+01, 4.7268e+01, 4.5598e+01,  ..., 5.4585e-03, 5.2656e-03,
         5.0795e-03]])


In [6]:
freqs_complex = torch.polar(torch.ones_like(freqs), freqs) # (seq_len, head_dim // 2)
print(freqs_complex.shape)
print(freqs_complex)

torch.Size([50, 256])
tensor([[ 1.0000+0.0000e+00j,  1.0000+0.0000e+00j,  1.0000+0.0000e+00j,
          ...,  1.0000+0.0000e+00j,  1.0000+0.0000e+00j,
          1.0000+0.0000e+00j],
        [ 0.5403+8.4147e-01j,  0.5697+8.2186e-01j,  0.5974+8.0196e-01j,
          ...,  1.0000+1.1140e-04j,  1.0000+1.0746e-04j,
          1.0000+1.0366e-04j],
        [-0.4161+9.0930e-01j, -0.3509+9.3641e-01j, -0.2863+9.5814e-01j,
          ...,  1.0000+2.2279e-04j,  1.0000+2.1492e-04j,
          1.0000+2.0733e-04j],
        ...,
        [-0.9923+1.2357e-01j,  0.2124+9.7719e-01j,  0.9700-2.4296e-01j,
          ...,  1.0000+5.2357e-03j,  1.0000+5.0506e-03j,
          1.0000+4.8722e-03j],
        [-0.6401-7.6825e-01j, -0.6821+7.3123e-01j,  0.7743+6.3280e-01j,
          ...,  1.0000+5.3470e-03j,  1.0000+5.1581e-03j,
          1.0000+4.9758e-03j],
        [ 0.3006-9.5375e-01j, -0.9896-1.4403e-01j, -0.0449+9.9899e-01j,
          ...,  1.0000+5.4584e-03j,  1.0000+5.2656e-03j,
          1.0000+5.0795e-03j]])


In [7]:
freqs_complex = freqs_complex.unsqueeze(0).unsqueeze(2)
print(freqs_complex.shape)
print(freqs_complex)

torch.Size([1, 50, 1, 256])
tensor([[[[ 1.0000+0.0000e+00j,  1.0000+0.0000e+00j,  1.0000+0.0000e+00j,
            ...,  1.0000+0.0000e+00j,  1.0000+0.0000e+00j,
            1.0000+0.0000e+00j]],

         [[ 0.5403+8.4147e-01j,  0.5697+8.2186e-01j,  0.5974+8.0196e-01j,
            ...,  1.0000+1.1140e-04j,  1.0000+1.0746e-04j,
            1.0000+1.0366e-04j]],

         [[-0.4161+9.0930e-01j, -0.3509+9.3641e-01j, -0.2863+9.5814e-01j,
            ...,  1.0000+2.2279e-04j,  1.0000+2.1492e-04j,
            1.0000+2.0733e-04j]],

         ...,

         [[-0.9923+1.2357e-01j,  0.2124+9.7719e-01j,  0.9700-2.4296e-01j,
            ...,  1.0000+5.2357e-03j,  1.0000+5.0506e-03j,
            1.0000+4.8722e-03j]],

         [[-0.6401-7.6825e-01j, -0.6821+7.3123e-01j,  0.7743+6.3280e-01j,
            ...,  1.0000+5.3470e-03j,  1.0000+5.1581e-03j,
            1.0000+4.9758e-03j]],

         [[ 0.3006-9.5375e-01j, -0.9896-1.4403e-01j, -0.0449+9.9899e-01j,
            ...,  1.0000+5.4584e-03j,  1.00

In [9]:
x = torch.randn(2, 3, 4)
x_out = x.view(-1)  # 将 x 展平为一维张量
print(x_out.shape)  # 输出: torch.Size([24])
print(x.shape)  # 输出: torch.Size([2, 3, 4])
# 恢复原始形状
x_out = x_out.reshape(*x.shape)
print(x_out.shape)  # 输出: torch.Size([2, 3, 4])

torch.Size([24])
torch.Size([2, 3, 4])
torch.Size([2, 3, 4])


In [3]:
import torch
xv = torch.randn(2, 1, 4 * 8)  # (batch_size, seq_len, n_kv_heads, head_dim)
print(xv.shape)  # 输出: torch.Size([2, 1, 32])
print(xv)  # 输出: torch.Size([2, 1, 32])
xv = xv.view(2, 1, 4, 8)
print(xv.shape)  # 输出: torch.Size([2, 1, 4, 8])
print(xv)  # 输出: torch.Size([2, 1, 4, 8])

torch.Size([2, 1, 32])
tensor([[[-1.7119, -0.6238,  1.2966, -1.5179, -0.8024,  0.0972, -0.1130,
           0.2210, -0.8717,  0.4642, -0.1666,  0.8681, -0.6419,  1.1976,
           0.1588,  0.0296,  0.4977, -0.9627,  0.9757, -0.0344, -1.1736,
          -0.6621, -1.2480, -2.4556,  0.8961, -0.4940, -0.3429,  0.9140,
           0.9383, -1.6185,  0.1193,  0.5649]],

        [[-1.5016, -1.8427, -1.0824,  1.3299,  1.0359, -0.9566, -0.9530,
          -0.1997,  0.1147, -1.4508,  0.6441,  0.2795, -1.6603,  0.8407,
          -0.5727,  0.4687,  0.4529, -0.3798,  1.7747,  0.8649, -1.5104,
          -0.0817,  0.0550, -2.2322,  0.7553,  1.5436,  0.9006,  0.4745,
           0.7986, -0.6604,  1.5986, -1.0017]]])
torch.Size([2, 1, 4, 8])
tensor([[[[-1.7119, -0.6238,  1.2966, -1.5179, -0.8024,  0.0972, -0.1130,
            0.2210],
          [-0.8717,  0.4642, -0.1666,  0.8681, -0.6419,  1.1976,  0.1588,
            0.0296],
          [ 0.4977, -0.9627,  0.9757, -0.0344, -1.1736, -0.6621, -1.2480,
      